// Polish language labels for the entire application
export const LABELS = {
  app: {
    title: 'WEBLE - Instrukcje Montażu',
    subtitle: 'AI-wspierane instrukcje montażu mebli',
  },
  upload: {
    title: 'Przesyłanie pliku STEP',
    drag: 'Przeciągnij plik tutaj lub kliknij aby wybrać',
    button: 'Wybierz plik',
    submitting: 'Przesyłanie...',
    size: 'Maksymalny rozmiar: 50 MB',
    error: 'Błąd przesyłania pliku',
    retry: 'Spróbuj ponownie',
    success: 'Plik przesłany pomyślnie',
    loading: 'Ładowanie...',
  },
  tone: {
    title: 'Wybierz styl instrukcji',
    subtitle: 'Jak chcesz aby brzmiały instrukcje montażu?',
    ikea: {
      label: 'IKEA',
      description: 'Przyjazny i zachęcający styl, łatwy do zrozumienia',
    },
    technical: {
      label: 'Techniczny',
      description: 'Precyzyjny i szczegółowy, dla inżynierów',
    },
    beginner: {
      label: 'Początkujący',
      description: 'Bardzo szczegółowy, z wskazówkami i ostrzeżeniami',
    },
    confirm: 'Potwierdź wybór',
  },
  viewer: {
    title: 'Przeglądarka modelu',
    progress: 'Postęp: {{percent}}%',
    eta: 'Szacunkowy czas: {{seconds}}s',
    stages: {
      loading: 'Ładowanie geometrii',
      extracting: 'Wyodrębnianie części',
      drawing: 'Generowanie rysunków',
      assembly: 'Generowanie instrukcji',
    },
    tabs: {
      overview: 'Przegląd',
      parts: 'Części',
      steps: 'Kroki',
    },
    complete: 'Analiza zakończona',
    next: 'Następny krok',
    error: 'Błąd podczas przetwarzania',
  },
  parts: {
    title: 'Lista części',
    type: 'Typ',
    quantity: 'Ilość',
    volume: 'Objętość (cm³)',
    dimensions: 'Wymiary',
    panel: 'Panel',
    fastener: 'Łącznik',
    hardware: 'Okucie',
    structural: 'Konstrukcja',
    other: 'Inne',
    export: 'Eksportuj SVG',
    uniqueParts: 'unikatowe części',
    totalParts: 'części łącznie',
    goToAssembly: 'Do instrukcji montażu',
    searchPlaceholder: 'Szukaj części...',
    basicInfo: 'Informacje podstawowe',
    width: 'Szerokość',
    height: 'Wysokość',
    depth: 'Głębokość',
    svgDiagram: 'Diagram SVG',
    svgComingSoon: 'Diagram SVG wkrótce',
    copy: 'Kopiuj',
    print: 'Drukuj',
    selectPart: 'Wybierz część aby zobaczyć szczegóły',
  },
  assembly: {
    title: 'Instrukcja montażu',
    step: 'Krok',
    of: 'z',
    description: 'Opis',
    detailedDescription: 'Szczegółowy opis',
    sequence: 'Sekwencja akcji',
    warnings: 'Ostrzeżenia',
    tips: 'Wskazówki',
    duration: 'Czas montażu',
    export: 'Eksportuj do PDF',
    print: 'Drukuj',
    previous: 'Poprzedni',
    next: 'Następny',
    confidence: 'Zaufanie',
    llmGenerated: 'Wygenerowane przez AI',
    rulesGenerated: 'Wygenerowane z reguł',
    partsForThisStep: 'Części na tym kroku',
    previouslyAssembled: 'Wcześniej zmontowane',
  },
  pdf: {
    title: 'Eksport do PDF',
    options: 'Opcje eksportu',
    include3DPreview: 'Dołącz podgląd modelu 3D',
    includePartsList: 'Dołącz listę części',
    includeSteps: 'Dołącz kroki montażu',
    colorMode: 'Kolor',
    bwMode: 'Czarno-białe',
    download: 'Pobierz PDF',
    generating: 'Generowanie PDF...',
    cancel: 'Anuluj',
  },
  errors: {
    fileInvalid: 'Plik jest nieprawidłowy lub zbyt mały',
    fileTooLarge: 'Plik jest za duży',
    networkError: 'Błąd połączenia sieciowego',
    apiError: 'Błąd serwera',
    parseError: 'Błąd analizy danych',
    tryAgain: 'Spróbuj ponownie',
    goHome: 'Wróć do głównej strony',
  },
  common: {
    loading: 'Ładowanie...',
    error: 'Błąd',
    success: 'Sukces',
    cancel: 'Anuluj',
    close: 'Zamknij',
    save: 'Zapisz',
    delete: 'Usuń',
    upload: 'Przesyłaj',
  },
};
